package models;

public class Kit {

    public enum KitName {

        BERSERKER, DEMOLITIONS, DWARF, EQUALITY, EXPLOSIVE, FROST, GHOST, JUGGERNAUT, LONGBOW, MEDIC, NINJA, PYRO, REWIND, SHORTBOW, SPY, TELEPORTER, TROOPER, VAMPIRE, VENOM, WARPER

    }

}
